# Generated by Django 4.1.5 on 2023-02-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="profile",
        ),
    ]
